<a href="https://colab.research.google.com/github/danielmancovidales/Aplicaciones-en-salud/blob/main/prepro_cronicos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Librerias generales
import pandas as pd
import numpy as np
import re
# Librerias y visualización
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# Leer base de datos
df_cronicos = pd.read_csv('/content/drive/MyDrive/analitica3/Salud/RETO_df_cronicos.csv', encoding='latin1', sep=';', low_memory= False)
df_cronicos

,YEAR,MES,Fecha diligenciamiento,Hora,AtenciÃ³n,Ingreso,Tipo,NRODOC,Peso,Talla,...,Diagnostico79,NombreDiagnostico79,Diagnostico80,NombreDiagnostico80,Diagnostico81,NombreDiagnostico81,Diagnostico82,NombreDiagnostico82,Diagnostico83,NombreDiagnostico83
0,2017,OCTUBRE,2/10/2017,9:00:20 a. m.,3912499,2629714,CC,311144,69.0,155.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017,OCTUBRE,2/10/2017,9:04:33 a. m.,3942247,2629726,CC,308418,62.0,155.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017,OCTUBRE,2/10/2017,9:11:43 a. m.,3898560,2629751,CC,308573,89.0,163.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017,OCTUBRE,2/10/2017,9:33:34 a. m.,3912599,2629828,CC,307549,88.0,163.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017,OCTUBRE,2/10/2017,9:43:59 a. m.,3906820,2629717,CC,307044,58.0,158.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38712,2022,MAYO,31/05/2022,10:55:31 p.m.,3419528,3630125,CC,308916,65.0,165.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38713,2022,MAYO,31/05/2022,10:59:58 p.m.,5850632,4314997,CC,306248,60.0,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38714,2022,MAYO,31/05/2022,11:13:57 p.m.,3413909,3630054,CC,310546,48.0,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38715,2022,MAYO,31/05/2022,11:17:35 p.m.,5783823,4089709,CC,309601,60.0,165.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38716,2022,MAYO,31/05/2022,11:25:39 p.m.,3991645,3434751,CC,311850,75.0,164.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**NÚMERO DE DIAGNOSTICOS**

In [4]:
# Seleccionar todas las columnas que siguen el patrón 'nombrediagnosticoX' (donde X es un número)
columnas_seleccionadas = df_cronicos.filter(like='NombreDiagnostico')

In [5]:
# Crear un nuevo DataFrame con las columnas seleccionadas
nuevo_df = df_cronicos[columnas_seleccionadas.columns]

nuevo_df

,NombreDiagnostico1,NombreDiagnostico2,NombreDiagnostico3,NombreDiagnostico4,NombreDiagnostico5,NombreDiagnostico6,NombreDiagnostico7,NombreDiagnostico8,NombreDiagnostico9,NombreDiagnostico10,...,NombreDiagnostico74,NombreDiagnostico75,NombreDiagnostico76,NombreDiagnostico77,NombreDiagnostico78,NombreDiagnostico79,NombreDiagnostico80,NombreDiagnostico81,NombreDiagnostico82,NombreDiagnostico83
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38712,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38713,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38714,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38715,7/09/2022 0:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38716,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
valores_no_nulos_por_fila = nuevo_df.count(axis=1)
nuevo_df['Valores_No_Nulos_Por_Fila'] = valores_no_nulos_por_fila

<ipython-input-6-d738a93d88c4>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  nuevo_df['Valores_No_Nulos_Por_Fila'] = valores_no_nulos_por_fila

In [7]:
nuevo_df['Valores_No_Nulos_Por_Fila']

0        0
1        0
2        0
3        0
4        0
        ..
38712    0
38713    0
38714    0
38715    1
38716    0
Name: Valores_No_Nulos_Por_Fila, Length: 38717, dtype: int64

In [8]:
df_cronicos['numero_diagnosticos']=nuevo_df['Valores_No_Nulos_Por_Fila']

In [9]:
nuevo_df=nuevo_df.drop('Valores_No_Nulos_Por_Fila', axis=1)

In [10]:
columnas_a_eliminar = set(nuevo_df.columns)
df_cronicos = df_cronicos.drop(columns=columnas_a_eliminar)

In [11]:
df_cronicos

,YEAR,MES,Fecha diligenciamiento,Hora,AtenciÃ³n,Ingreso,Tipo,NRODOC,Peso,Talla,...,Diagnostico75,Diagnostico76,Diagnostico77,Diagnostico78,Diagnostico79,Diagnostico80,Diagnostico81,Diagnostico82,Diagnostico83,numero_diagnosticos
0,2017,OCTUBRE,2/10/2017,9:00:20 a. m.,3912499,2629714,CC,311144,69.0,155.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,2017,OCTUBRE,2/10/2017,9:04:33 a. m.,3942247,2629726,CC,308418,62.0,155.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,2017,OCTUBRE,2/10/2017,9:11:43 a. m.,3898560,2629751,CC,308573,89.0,163.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,2017,OCTUBRE,2/10/2017,9:33:34 a. m.,3912599,2629828,CC,307549,88.0,163.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,2017,OCTUBRE,2/10/2017,9:43:59 a. m.,3906820,2629717,CC,307044,58.0,158.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38712,2022,MAYO,31/05/2022,10:55:31 p.m.,3419528,3630125,CC,308916,65.0,165.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
38713,2022,MAYO,31/05/2022,10:59:58 p.m.,5850632,4314997,CC,306248,60.0,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
38714,2022,MAYO,31/05/2022,11:13:57 p.m.,3413909,3630054,CC,310546,48.0,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
38715,2022,MAYO,31/05/2022,11:17:35 p.m.,5783823,4089709,CC,309601,60.0,165.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
38716,2022,MAYO,31/05/2022,11:25:39 p.m.,3991645,3434751,CC,311850,75.0,164.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [12]:
# Verificar nombres de columnas
df_cronicos.columns

Index(['YEAR', 'MES', 'Fecha diligenciamiento', 'Hora', 'AtenciÃ³n', 'Ingreso',
       'Tipo', 'NRODOC', 'Peso', 'Talla',
       ...
       'Diagnostico75', 'Diagnostico76', 'Diagnostico77', 'Diagnostico78',
       'Diagnostico79', 'Diagnostico80', 'Diagnostico81', 'Diagnostico82',
       'Diagnostico83', 'numero_diagnosticos'],
      dtype='object', length=207)

In [13]:
df_cronicos.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38717 entries, 0 to 38716
Data columns (total 207 columns):
 #    Column                                                                       Dtype
---   ------                                                                       -----
 0    YEAR                                                                         int64
 1    MES                                                                          object
 2    Fecha diligenciamiento                                                       object
 3    Hora                                                                         object
 4    AtenciÃ³n                                                                    int64
 5    Ingreso                                                                      int64
 6    Tipo                                                                         object
 7    NRODOC                                                                       int64
 8    Peso                                                                         float64
 9    Talla                                                                        float64
 10   IMC                                                                          float64
 11   ClasificaciÃ³n IMC                                                           object
 12   SaturaciÃ³n de OxÃ­geno (%)                                                  float64
 13   PerÃ­metro Muslo                                                             int64
 14   PerÃ­metro Cintura                                                           float64
 15   Pliegue Triceps                                                              float64
 16   Pliegue Abdomen                                                              float64
 17   Pliegue Muslo                                                                float64
 18   Sumatoria Pliegues                                                           float64
 19   PresiÃ³n Arterial SistÃ³lica                                                 int64
 20   PresiÃ³n Arterial DiastÃ³lica                                                int64
 21   Frecuencia CardÃ­aca en reposo                                               int64
 22   Auto-calificacion Nivel de Ejercicio                                         int64
 23   Constantes                                                                   float64
 24   METS -Ãndice MetabÃ³lico                                                    float64
 25   VO2 - MÃ¡xima Cantidad de OxÃ­geno                                           float64
 26   Ãndice de Fragilidad Groningen                                              float64
 27   CalificaciÃ³n (Ãndice de Fragilidad)                                        object
 28   Tiempo en Segundos (Apoyo Monopodal)                                         int64
 29   CalificaciÃ³n (Apoyo Monopodal)                                              object
 30   Tiempo en Segundos (Recorrer 5 metros)                                       int64
 31   Velocidad (m/s)                                                              float64
 32   CalificaciÃ³n Velocidad                                                      object
 33   Test Findrisc                                                                object
 34   Ãndice Tobillo/Brazo                                                        object
 35   Observaciones                                                                object
 36   PresiÃ³n arterial registro medico                                            object
 37   Diabetes Mellitus                                                            object
 38   Tipo diabetes mellitus                                                       object
 39   Es insulinorequiriente                                                       object
 40   Tiempo con el diagnÃ³stico                                                   object
 41   Glicemia                                                                     float64
 42   Fecha glicemia                                                               object
 43   Hemoglobina Glicada                                                          float64
 44   Fecha hemoglobina glicosilada                                                object
 45   Control Diabetes                                                             object
 46   Tiene riesgo de tener Diabetes Mellitus                                      object
 47   Tiene HTA                                                                    object
 48   Control HTA                                                                  object
 49   Tiene riesgo de tener HTA                                                    object
 50   Tiempo con el diagnÃ³stico1                                                  object
 51   Tiene EPOC                                                                   object
 52   Espirometria                                                                 object
 53   VEF1/CVF                                                                     float64
 54   VEF1/VFC Posbroncodilatador                                                  float64
 55   Gravedad                                                                     object
 56   DiagnÃ³stico EPOC                                                            object
 57   Disnea MMRC                                                                  float64
 58   ClasificaciÃ³n                                                               object
 59   CAT                                                                          float64
 60   NÃºmero de exacerbaciones Ãºltimo aÃ±o (Que hayan necesitado hospitalizado)  float64
 61   ClasificaciÃ³n GOLD                                                          float64
 62   ClasificaciÃ³n1                                                              object
 63   ClasificaciÃ³n BODEX                                                         float64
 64   OxÃ­geno dependiente                                                         object
 65   Tiene gases arteriales                                                       object
 66   Resultado                                                                    object
 67   EPOC (ClasificaciÃ³n BODEX)                                                  object
 68   Enfermedad Coronaria (En el Ãºltimo aÃ±o)                                    object
 69   Insuficiencia CardÃ­aca                                                      object
 70   ValvulopatÃ­a                                                                object
 71   Arritmia o paciente con dispositivo                                          object
 72   Sufre de alguna enfermedad cardiovascular                                    object
 73   Â¿CuÃ¡l?                                                                     object
 74   Tabaquismo                                                                   object
 75   Cuantos cigarrillos dÃ­a                                                     object
 76   AÃ±os de Consumo                                                             float64
 77   Indice paquete/aÃ±o                                                          float64
 78   Lipoproteina                                                                 float64
 79   Fecha LDL                                                                    object
 80   HDL                                                                          float64
 81   Fecha HDL                                                                    object
 82   Colesterol total                                                             float64
 83   Fecha colesterol total                                                       object
 84   Trigliceridos                                                                float64
 85   Fecha trigliceridos                                                          object
 86   ClasificaciÃ³n de Framinghan                                                 object
 87   Creatinina 1 consulta                                                        float64
 88   Fecha creatinina1                                                            object
 89   Tasa de FiltraciÃ³n Glomerular TFG                                           float64
 90   Estadio de la Enfermedad Renal                                               object
 91   Microalbuminuria                                                             float64
 92   Fecha microalbuminuria                                                       object
 93   Hormona Estimulante de la Tiroides (TSH)                                     float64
 94   Otras Morbilidades                                                           float64
 95   Clase Funcional                                                              object
 96   Creatinina 2 consulta                                                        float64
 97   Fecha creatinina2                                                            object
 98   Tasa de FiltraciÃ³n Glomerular TFG2                                          float64
 99   Meses de diferencia entre TFG                                                float64
 100  Cambio de TFG                                                                float64
 101  ClasificaciÃ³n Cambio de TFG                                                 object
 102  Ãltima mamografÃ­a                                                          object
 103  Ãltima citologÃ­a                                                           object
 104  Ãltima cita odontolÃ³gica                                                   object
 105  Ãltima cita con OptometrÃ­a / OftallmologÃ­a                                object
 106  Ãltimo PSA                                                                  object
 107  Basciloscopia                                                                object
 108  Fecha basciloscopia                                                          object
 109  Ãltima vacuna de influenza                                                  object
 110  Fecha Vacuna Neumococo                                                       object
 111  Fecha vacuna neumococo veintitrÃ©s valentes                                  object
 112  Ãlcera de pie diabÃ©tico                                                    object
 113  RemisiÃ³n                                                                    object
 114  DiagnÃ³stico Principal                                                       object
 115  AnÃ¡lisis y conducta a seguir                                                object
 116  Tiene prÃ³ximo control                                                       object
 117  Fecha PrÃ³ximo Control                                                       object
 118  Tipo control                                                                 object
 119  Requiere cita de morbilidad                                                  object
 120  Fecha cita morbilidad                                                        object
 121  Ambito segÃºn el mÃ©dico                                                     object
 122  Diagnostico1                                                                 object
 123  Diagnostico2                                                                 object
 124  Diagnostico3                                                                 object
 125  Diagnostico4                                                                 object
 126  Diagnostico5                                                                 object
 127  Diagnostico6                                                                 object
 128  Diagnostico7                                                                 object
 129  Diagnostico8                                                                 object
 130  Diagnostico9                                                                 object
 131  Diagnostico10                                                                object
 132  Diagnostico11                                                                object
 133  Diagnostico12                                                                object
 134  Diagnostico13                                                                object
 135  Diagnostico14                                                                object
 136  Diagnostico15                                                                object
 137  Diagnostico16                                                                object
 138  Diagnostico17                                                                object
 139  Diagnostico18                                                                object
 140  Diagnostico19                                                                object
 141  Diagnostico20                                                                object
 142  Diagnostico21                                                                object
 143  Diagnostico22                                                                object
 144  Diagnostico23                                                                object
 145  Diagnostico24                                                                object
 146  Diagnostico25                                                                object
 147  Diagnostico26                                                                object
 148  Diagnostico26.1                                                              object
 149  Diagnostico27                                                                object
 150  Diagnostico28                                                                object
 151  Diagnostico29                                                                object
 152  Diagnostico30                                                                object
 153  Diagnostico31                                                                object
 154  Diagnostico32                                                                object
 155  Diagnostico33                                                                object
 156  Diagnostico34                                                                object
 157  Diagnostico35                                                                object
 158  Diagnostico36                                                                object
 159  Diagnostico37                                                                object
 160  Diagnostico38                                                                object
 161  Diagnostico39                                                                object
 162  Diagnostico40                                                                object
 163  Diagnostico41                                                                object
 164  Diagnostico42                                                                object
 165  Diagnostico43                                                                object
 166  Diagnostico44                                                                object
 167  Diagnostico45                                                                object
 168  Diagnostico46                                                                object
 169  Diagnostico47                                                                object
 170  Diagnostico48                                                                object
 171  Diagnostico49                                                                object
 172  Diagnostico50                                                                object
 173  Diagnostico51                                                                object
 174  Diagnostico52                                                                object
 175  Diagnostico53                                                                object
 176  Diagnostico54                                                                object
 177  Diagnostico55                                                                object
 178  Diagnostico56                                                                object
 179  Diagnostico57                                                                object
 180  Diagnostico58                                                                object
 181  Diagnostico59                                                                object
 182  Diagnostico60                                                                object
 183  Diagnostico61                                                                object
 184  Diagnostico62                                                                object
 185  Diagnostico63                                                                object
 186  Diagnostico64                                                                object
 187  Diagnostico65                                                                object
 188  Diagnostico66                                                                object
 189  Diagnostico67                                                                object
 190  Diagnostico68                                                                object
 191  Diagnostico69                                                                object
 192  Diagnostico70                                                                object
 193  Diagnostico71                                                                object
 194  Diagnostico72                                                                object
 195  Diagnostico73                                                                object
 196  Diagnostico74                                                                object
 197  Diagnostico75                                                                object
 198  Diagnostico76                                                                object
 199  Diagnostico77                                                                object
 200  Diagnostico78                                                                object
 201  Diagnostico79                                                                object
 202  Diagnostico80                                                                object
 203  Diagnostico81                                                                object
 204  Diagnostico82                                                                object
 205  Diagnostico83                                                                object
 206  numero_diagnosticos                                                          int64
dtypes: float64(38), int64(12), object(157)
memory usage: 61.1+ MB

In [14]:
# Estadísticas de los datos
df_cronicos.describe(include = 'all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
YEAR,38717.0,NaN,NaN,NaN,2020.178242,1.733891,2017.0,2018.0,2021.0,2021.0,2022.0
MES,38717,12,MARZO,4712,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fecha diligenciamiento,38717,779,27/10/2021,129,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hora,38717,30961,11:12:08 a.m.,649,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AtenciÃ³n,38717.0,NaN,NaN,NaN,5047904.406824,823072.365209,3408530.0,4255222.0,5377653.0,5800403.0,6125234.0
...,...,...,...,...,...,...,...,...,...,...,...
Diagnostico80,16,12,F001,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Diagnostico81,15,11,F319,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Diagnostico82,13,11,F319,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Diagnostico83,13,11,F319,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
numero_diagnosticos,38717.0,NaN,NaN,NaN,1.304724,4.28053,0.0,0.0,0.0,1.0,84.0

**Normalización de caracteres especiales**

In [15]:
# Se corrigen los nombres que tienen tildes y simbolos
df_cronicos = df_cronicos.rename(columns={'AtenciÃ³n': 'Atencion'})
df_cronicos = df_cronicos.rename(columns={'ClasificaciÃ³n IMC': 'Clasificacion IMC'})
df_cronicos = df_cronicos.rename(columns={'SaturaciÃ³n de OxÃ­geno (%)': 'Saturacion de Oxigeno (%)'})
df_cronicos = df_cronicos.rename(columns={'PerÃ­metro Muslo': 'Perimetro Muslo'})
df_cronicos = df_cronicos.rename(columns={'PerÃ­metro Cintura': 'Perimetro Cintura'})
df_cronicos = df_cronicos.rename(columns={'PresiÃ³n Arterial SistÃ³lica': 'Presion Arterial Sistolica'})
df_cronicos = df_cronicos.rename(columns={'PresiÃ³n Arterial DiastÃ³lica': 'Presion Arterial Diastolica'})
df_cronicos = df_cronicos.rename(columns={'Frecuencia CardÃ­aca en reposo': 'Frecuencia Cardiaca en reposo'})
df_cronicos = df_cronicos.rename(columns={'METS -Ãndice MetabÃ³lico': 'METS -indice Metabolico'})
df_cronicos = df_cronicos.rename(columns={'VO2 - MÃ¡xima Cantidad de OxÃ­geno': 'VO2 - Maxima Cantidad de Oxigeno'})
df_cronicos = df_cronicos.rename(columns={'Ãndice de Fragilidad Groningen': 'indice de Fragilidad Groningen'})
df_cronicos = df_cronicos.rename(columns={'CalificaciÃ³n (Ãndice de Fragilidad)': 'Calificacion (indice de Fragilidad)'})
df_cronicos = df_cronicos.rename(columns={'CalificaciÃ³n (Apoyo Monopodal)': 'Calificacion (Apoyo Monopodal)'})
df_cronicos = df_cronicos.rename(columns={'CalificaciÃ³n Velocidad': 'Calificacion Velocidad'})
df_cronicos = df_cronicos.rename(columns={'Ãndice Tobillo/Brazo': 'indice Tobillo/Brazo'})
df_cronicos = df_cronicos.rename(columns={'PresiÃ³n arterial registro medico': 'Presion arterial registro medico'})
df_cronicos = df_cronicos.rename(columns={'Tiempo con el diagnÃ³stico': 'Tiempo con el diagnostico'})
df_cronicos = df_cronicos.rename(columns={'Tiempo con el diagnÃ³stico1': 'Tiempo con el diagnostico1'})
df_cronicos = df_cronicos.rename(columns={'DiagnÃ³stico EPOC': 'Diagnostico EPOC'})
df_cronicos = df_cronicos.rename(columns={'ClasificaciÃ³n': 'Clasificacion'})
df_cronicos = df_cronicos.rename(columns={'NÃºmero de exacerbaciones Ãºltimo aÃ±o (Que hayan necesitado hospitalizado)': 'Numero de exacerbaciones ultimo ano (Que hayan necesitado hospitalizado)'})
df_cronicos = df_cronicos.rename(columns={'ClasificaciÃ³n GOLD': 'Clasificacion GOLD'})
df_cronicos = df_cronicos.rename(columns={'ClasificaciÃ³n1': 'Clasificacion1'})
df_cronicos = df_cronicos.rename(columns={'ClasificaciÃ³n BODEX': 'Clasificacion BODEX'})
df_cronicos = df_cronicos.rename(columns={'OxÃ­geno dependiente': 'Oxigeno dependiente'})
df_cronicos = df_cronicos.rename(columns={'EPOC (ClasificaciÃ³n BODEX)': 'EPOC (Clasificacion BODEX)'})
df_cronicos = df_cronicos.rename(columns={'Insuficiencia CardÃ­aca': 'Insuficiencia Cardiaca'})
df_cronicos = df_cronicos.rename(columns={'ValvulopatÃ­a': 'Valvulopatia'})
df_cronicos = df_cronicos.rename(columns={'Â¿CuÃ¡l?': 'i¿Cual?'})
df_cronicos = df_cronicos.rename(columns={'Cuantos cigarrillos dÃ­a': 'Cuantos cigarrillos dia'})
df_cronicos = df_cronicos.rename(columns={'AÃ±os de Consumo': 'Anos de Consumo'})
df_cronicos = df_cronicos.rename(columns={'Indice paquete/aÃ±o': 'Indice paquete/ano'})
df_cronicos = df_cronicos.rename(columns={'ClasificaciÃ³n de Framinghan': 'Clasificacion de Framinghan'})
df_cronicos = df_cronicos.rename(columns={'Tasa de FiltraciÃ³n Glomerular TFG': 'Tasa de Filtracion Glomerular TFG'})
df_cronicos = df_cronicos.rename(columns={'Tasa de FiltraciÃ³n Glomerular TFG2': 'Tasa de Filtracion Glomerular TFG2'})
df_cronicos = df_cronicos.rename(columns={'ClasificaciÃ³n Cambio de TFG': 'Clasificacion Cambio de TFG'})
df_cronicos = df_cronicos.rename(columns={'Ãšltima mamografÃ­a': 'ultima mamografia'})
df_cronicos = df_cronicos.rename(columns={'Ãšltima citologÃ­a': 'ultima citologia'})
df_cronicos = df_cronicos.rename(columns={'Ãšltima cita odontolÃ³gica': 'ultima cita odontologica'})
df_cronicos = df_cronicos.rename(columns={'Ãšltima cita con OptometrÃ­a / OftallmologÃ­a': 'ultima cita con Optometria / Oftallmologia'})
df_cronicos = df_cronicos.rename(columns={'Ãšltimo PSA': 'ultimo PSA'})
df_cronicos = df_cronicos.rename(columns={'Ãšltima vacuna de influenza': 'ultima vacuna de influenza'})
df_cronicos = df_cronicos.rename(columns={'Fecha vacuna neumococo veintitrÃ©s valentes': 'Fecha vacuna neumococo veintitres valentes'})
df_cronicos = df_cronicos.rename(columns={'Ãšlcera de pie diabÃ©tico': 'ulcera de pie diabetico'})
df_cronicos = df_cronicos.rename(columns={'RemisiÃ³n': 'Remision'})
df_cronicos = df_cronicos.rename(columns={'DiagnÃ³stico Principal': 'Diagnostico Principal'})
df_cronicos = df_cronicos.rename(columns={'AnÃ¡lisis y conducta a seguir': 'Analisis y conducta a seguir'})
df_cronicos = df_cronicos.rename(columns={'Tiene prÃ³ximo control': 'Tiene proximo control'})
df_cronicos = df_cronicos.rename(columns={'Fecha PrÃ³ximo Control': 'Fecha Proximo Control'})
df_cronicos = df_cronicos.rename(columns={'Ambito segÃºn el mÃ©dico': 'Ambito segun el medico'})
df_cronicos = df_cronicos.rename(columns={'enfermedad_coronaria_(en_el_ãºltimo_aã±o)': 'enfermedad_coronaria_(en_el_ultimo_ano)'})

In [16]:
#colocar datos en minusculas

df_cronicos.columns = df_cronicos.columns.str.lower()
df_cronicos

,year,mes,fecha diligenciamiento,hora,atencion,ingreso,tipo,nrodoc,peso,talla,...,diagnostico75,diagnostico76,diagnostico77,diagnostico78,diagnostico79,diagnostico80,diagnostico81,diagnostico82,diagnostico83,numero_diagnosticos
0,2017,OCTUBRE,2/10/2017,9:00:20 a. m.,3912499,2629714,CC,311144,69.0,155.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,2017,OCTUBRE,2/10/2017,9:04:33 a. m.,3942247,2629726,CC,308418,62.0,155.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,2017,OCTUBRE,2/10/2017,9:11:43 a. m.,3898560,2629751,CC,308573,89.0,163.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,2017,OCTUBRE,2/10/2017,9:33:34 a. m.,3912599,2629828,CC,307549,88.0,163.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,2017,OCTUBRE,2/10/2017,9:43:59 a. m.,3906820,2629717,CC,307044,58.0,158.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38712,2022,MAYO,31/05/2022,10:55:31 p.m.,3419528,3630125,CC,308916,65.0,165.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
38713,2022,MAYO,31/05/2022,10:59:58 p.m.,5850632,4314997,CC,306248,60.0,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
38714,2022,MAYO,31/05/2022,11:13:57 p.m.,3413909,3630054,CC,310546,48.0,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
38715,2022,MAYO,31/05/2022,11:17:35 p.m.,5783823,4089709,CC,309601,60.0,165.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
38716,2022,MAYO,31/05/2022,11:25:39 p.m.,3991645,3434751,CC,311850,75.0,164.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [17]:
# Se reemplazan los nombres de los meses con un diccionario
categorias = {'ENERO':'Enero','FEBRERO':'Febrero','MARZO':'Marzo','ABRIL':'Abril','MAYO':'Mayo','JUNIO':'Junio','JULIO':'Julio','AGOSTO':'Agosto','SEPTIEMBRE':'Septiembre','OCTUBRE':'Octubre','NOVIEMBRE':'Noviembre','DICIEMBRE':'Diciembre'}
df_cronicos['mes'] = df_cronicos['mes'].replace(categorias)
df_cronicos

,year,mes,fecha diligenciamiento,hora,atencion,ingreso,tipo,nrodoc,peso,talla,...,diagnostico75,diagnostico76,diagnostico77,diagnostico78,diagnostico79,diagnostico80,diagnostico81,diagnostico82,diagnostico83,numero_diagnosticos
0,2017,Octubre,2/10/2017,9:00:20 a. m.,3912499,2629714,CC,311144,69.0,155.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,2017,Octubre,2/10/2017,9:04:33 a. m.,3942247,2629726,CC,308418,62.0,155.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,2017,Octubre,2/10/2017,9:11:43 a. m.,3898560,2629751,CC,308573,89.0,163.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,2017,Octubre,2/10/2017,9:33:34 a. m.,3912599,2629828,CC,307549,88.0,163.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,2017,Octubre,2/10/2017,9:43:59 a. m.,3906820,2629717,CC,307044,58.0,158.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38712,2022,Mayo,31/05/2022,10:55:31 p.m.,3419528,3630125,CC,308916,65.0,165.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
38713,2022,Mayo,31/05/2022,10:59:58 p.m.,5850632,4314997,CC,306248,60.0,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
38714,2022,Mayo,31/05/2022,11:13:57 p.m.,3413909,3630054,CC,310546,48.0,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
38715,2022,Mayo,31/05/2022,11:17:35 p.m.,5783823,4089709,CC,309601,60.0,165.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
38716,2022,Mayo,31/05/2022,11:25:39 p.m.,3991645,3434751,CC,311850,75.0,164.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [18]:
#Rellenar espacios con _
df_cronicos.columns = df_cronicos.columns.str.replace(' ', '_')

**Identificación de nulos**

In [19]:
#Filas duplicadas
filas_duplicadas = df_cronicos.duplicated(keep='first')
cantidad_duplicadas = filas_duplicadas.sum()
cantidad_duplicadas

2

In [20]:
#Eliminación de filas duplicadas
df_cronicos = df_cronicos.drop_duplicates()
df_cronicos

,year,mes,fecha_diligenciamiento,hora,atencion,ingreso,tipo,nrodoc,peso,talla,...,diagnostico75,diagnostico76,diagnostico77,diagnostico78,diagnostico79,diagnostico80,diagnostico81,diagnostico82,diagnostico83,numero_diagnosticos
0,2017,Octubre,2/10/2017,9:00:20 a. m.,3912499,2629714,CC,311144,69.0,155.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,2017,Octubre,2/10/2017,9:04:33 a. m.,3942247,2629726,CC,308418,62.0,155.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,2017,Octubre,2/10/2017,9:11:43 a. m.,3898560,2629751,CC,308573,89.0,163.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,2017,Octubre,2/10/2017,9:33:34 a. m.,3912599,2629828,CC,307549,88.0,163.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,2017,Octubre,2/10/2017,9:43:59 a. m.,3906820,2629717,CC,307044,58.0,158.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38712,2022,Mayo,31/05/2022,10:55:31 p.m.,3419528,3630125,CC,308916,65.0,165.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
38713,2022,Mayo,31/05/2022,10:59:58 p.m.,5850632,4314997,CC,306248,60.0,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
38714,2022,Mayo,31/05/2022,11:13:57 p.m.,3413909,3630054,CC,310546,48.0,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
38715,2022,Mayo,31/05/2022,11:17:35 p.m.,5783823,4089709,CC,309601,60.0,165.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
38716,2022,Mayo,31/05/2022,11:25:39 p.m.,3991645,3434751,CC,311850,75.0,164.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [21]:
#Nulos de todos
for columna in df_cronicos.columns:
    valores_nulos = df_cronicos[columna].isnull().sum()
    print(f'Columna {columna}: {valores_nulos} valores nulos')

Columna year: 0 valores nulos
Columna mes: 0 valores nulos
Columna fecha_diligenciamiento: 0 valores nulos
Columna hora: 0 valores nulos
Columna atencion: 0 valores nulos
Columna ingreso: 0 valores nulos
Columna tipo: 0 valores nulos
Columna nrodoc: 0 valores nulos
Columna peso: 0 valores nulos
Columna talla: 0 valores nulos
Columna imc: 0 valores nulos
Columna clasificacion_imc: 0 valores nulos
Columna saturacion_de_oxigeno_(%): 140 valores nulos
Columna perimetro_muslo: 0 valores nulos
Columna perimetro_cintura: 0 valores nulos
Columna pliegue_triceps: 0 valores nulos
Columna pliegue_abdomen: 0 valores nulos
Columna pliegue_muslo: 0 valores nulos
Columna sumatoria_pliegues: 0 valores nulos
Columna presion_arterial_sistolica: 0 valores nulos
Columna presion_arterial_diastolica: 0 valores nulos
Columna frecuencia_cardiaca_en_reposo: 0 valores nulos
Columna auto-calificacion_nivel_de_ejercicio: 0 valores nulos
Columna constantes: 0 valores nulos
Columna mets_-indice_metabolico: 0 valores nulos
Columna vo2_-_maxima_cantidad_de_oxigeno: 0 valores nulos
Columna indice_de_fragilidad_groningen: 47 valores nulos
Columna calificacion_(indice_de_fragilidad): 0 valores nulos
Columna tiempo_en_segundos_(apoyo_monopodal): 0 valores nulos
Columna calificacion_(apoyo_monopodal): 0 valores nulos
Columna tiempo_en_segundos_(recorrer_5_metros): 0 valores nulos
Columna velocidad_(m/s): 0 valores nulos
Columna calificacion_velocidad: 0 valores nulos
Columna test_findrisc: 12760 valores nulos
Columna indice_tobillo/brazo: 18640 valores nulos
Columna observaciones: 27589 valores nulos
Columna presion_arterial_registro_medico: 22905 valores nulos
Columna diabetes_mellitus: 871 valores nulos
Columna tipo_diabetes_mellitus: 13693 valores nulos
Columna es_insulinorequiriente: 25893 valores nulos
Columna tiempo_con_el_diagnostico: 14670 valores nulos
Columna glicemia: 871 valores nulos
Columna fecha_glicemia: 2454 valores nulos
Columna hemoglobina_glicada: 871 valores nulos
Columna fecha_hemoglobina_glicosilada: 3631 valores nulos
Columna control_diabetes: 871 valores nulos
Columna tiene_riesgo_de_tener_diabetes_mellitus: 27886 valores nulos
Columna tiene_hta: 871 valores nulos
Columna control_hta: 10721 valores nulos
Columna tiene_riesgo_de_tener_hta: 10721 valores nulos
Columna tiempo_con_el_diagnostico1: 7001 valores nulos
Columna tiene_epoc: 871 valores nulos
Columna espirometria: 38684 valores nulos
Columna vef1/cvf: 38346 valores nulos
Columna vef1/vfc_posbroncodilatador: 38346 valores nulos
Columna gravedad: 38693 valores nulos
Columna diagnostico_epoc: 38684 valores nulos
Columna disnea_mmrc: 38346 valores nulos
Columna clasificacion: 38695 valores nulos
Columna cat: 38346 valores nulos
Columna numero_de_exacerbaciones_ultimo_ano_(que_hayan_necesitado_hospitalizado): 38346 valores nulos
Columna clasificacion_gold: 38346 valores nulos
Columna clasificacion1: 38694 valores nulos
Columna clasificacion_bodex: 38346 valores nulos
Columna oxigeno_dependiente: 38685 valores nulos
Columna tiene_gases_arteriales: 38698 valores nulos
Columna resultado: 38673 valores nulos
Columna epoc_(clasificacion_bodex): 18000 valores nulos
Columna enfermedad_coronaria_(en_el_ãºltimo_aã±o): 871 valores nulos
Columna insuficiencia_cardiaca: 871 valores nulos
Columna valvulopatia: 871 valores nulos
Columna arritmia_o_paciente_con_dispositivo: 871 valores nulos
Columna sufre_de_alguna_enfermedad_cardiovascular: 871 valores nulos
Columna i¿cual?: 22144 valores nulos
Columna tabaquismo: 1053 valores nulos
Columna cuantos_cigarrillos_dia: 785 valores nulos
Columna anos_de_consumo: 13072 valores nulos
Columna indice_paquete/ano: 34579 valores nulos
Columna lipoproteina: 1053 valores nulos
Columna fecha_ldl: 12134 valores nulos
Columna hdl: 1053 valores nulos
Columna fecha_hdl: 2249 valores nulos
Columna colesterol_total: 1053 valores nulos
Columna fecha_colesterol_total: 2274 valores nulos
Columna trigliceridos: 1053 valores nulos
Columna fecha_trigliceridos: 2323 valores nulos
Columna clasificacion_de_framinghan: 8670 valores nulos
Columna creatinina_1_consulta: 1053 valores nulos
Columna fecha_creatinina1: 1786 valores nulos
Columna tasa_de_filtracion_glomerular_tfg: 1053 valores nulos
Columna estadio_de_la_enfermedad_renal: 3248 valores nulos
Columna microalbuminuria: 1053 valores nulos
Columna fecha_microalbuminuria: 4817 valores nulos
Columna hormona_estimulante_de_la_tiroides_(tsh): 1053 valores nulos
Columna otras_morbilidades: 38715 valores nulos
Columna clase_funcional: 1053 valores nulos
Columna creatinina_2_consulta: 1053 valores nulos
Columna fecha_creatinina2: 9965 valores nulos
Columna tasa_de_filtracion_glomerular_tfg2: 1053 valores nulos
Columna meses_de_diferencia_entre_tfg: 1053 valores nulos
Columna cambio_de_tfg: 1053 valores nulos
Columna clasificacion_cambio_de_tfg: 21929 valores nulos
Columna ãltima_mamografã­a: 37105 valores nulos
Columna ãltima_citologã­a: 37604 valores nulos
Columna ãltima_cita_odontolã³gica: 36221 valores nulos
Columna ãltima_cita_con_optometrã­a_/_oftallmologã­a: 34996 valores nulos
Columna ãltimo_psa: 36282 valores nulos
Columna basciloscopia: 20282 valores nulos
Columna fecha_basciloscopia: 35133 valores nulos
Columna ãltima_vacuna_de_influenza: 36540 valores nulos
Columna fecha_vacuna_neumococo: 37783 valores nulos
Columna fecha_vacuna_neumococo_veintitres_valentes: 38493 valores nulos
Columna ãlcera_de_pie_diabã©tico: 3504 valores nulos
Columna remision: 1053 valores nulos
Columna diagnostico_principal: 1350 valores nulos
Columna analisis_y_conducta_a_seguir: 1055 valores nulos
Columna tiene_proximo_control: 13570 valores nulos
Columna fecha_proximo_control: 14555 valores nulos
Columna tipo_control: 14279 valores nulos
Columna requiere_cita_de_morbilidad: 13570 valores nulos
Columna fecha_cita_morbilidad: 23847 valores nulos
Columna ambito_segun_el_medico: 13067 valores nulos
Columna diagnostico1: 28749 valores nulos
Columna diagnostico2: 30551 valores nulos
Columna diagnostico3: 32079 valores nulos
Columna diagnostico4: 33922 valores nulos
Columna diagnostico5: 35441 valores nulos
Columna diagnostico6: 36402 valores nulos
Columna diagnostico7: 37031 valores nulos
Columna diagnostico8: 37436 valores nulos
Columna diagnostico9: 37675 valores nulos
Columna diagnostico10: 37893 valores nulos
Columna diagnostico11: 37998 valores nulos
Columna diagnostico12: 38077 valores nulos
Columna diagnostico13: 38110 valores nulos
Columna diagnostico14: 38197 valores nulos
Columna diagnostico15: 38221 valores nulos
Columna diagnostico16: 38257 valores nulos
Columna diagnostico17: 38290 valores nulos
Columna diagnostico18: 38319 valores nulos
Columna diagnostico19: 38328 valores nulos
Columna diagnostico20: 38367 valores nulos
Columna diagnostico21: 38373 valores nulos
Columna diagnostico22: 38407 valores nulos
Columna diagnostico23: 38434 valores nulos
Columna diagnostico24: 38442 valores nulos
Columna diagnostico25: 38454 valores nulos
Columna diagnostico26: 38487 valores nulos
Columna diagnostico26.1: 38499 valores nulos
Columna diagnostico27: 38512 valores nulos
Columna diagnostico28: 38524 valores nulos
Columna diagnostico29: 38539 valores nulos
Columna diagnostico30: 38545 valores nulos
Columna diagnostico31: 38560 valores nulos
Columna diagnostico32: 38560 valores nulos
Columna diagnostico33: 38573 valores nulos
Columna diagnostico34: 38578 valores nulos
Columna diagnostico35: 38578 valores nulos
Columna diagnostico36: 38594 valores nulos
Columna diagnostico37: 38602 valores nulos
Columna diagnostico38: 38603 valores nulos
Columna diagnostico39: 38603 valores nulos
Columna diagnostico40: 38609 valores nulos
Columna diagnostico41: 38621 valores nulos
Columna diagnostico42: 38625 valores nulos
Columna diagnostico43: 38633 valores nulos
Columna diagnostico44: 38633 valores nulos
Columna diagnostico45: 38639 valores nulos
Columna diagnostico46: 38644 valores nulos
Columna diagnostico47: 38647 valores nulos
Columna diagnostico48: 38649 valores nulos
Columna diagnostico49: 38660 valores nulos
Columna diagnostico50: 38662 valores nulos
Columna diagnostico51: 38667 valores nulos
Columna diagnostico52: 38669 valores nulos
Columna diagnostico53: 38669 valores nulos
Columna diagnostico54: 38672 valores nulos
Columna diagnostico55: 38675 valores nulos
Columna diagnostico56: 38679 valores nulos
Columna diagnostico57: 38681 valores nulos
Columna diagnostico58: 38681 valores nulos
Columna diagnostico59: 38682 valores nulos
Columna diagnostico60: 38682 valores nulos
Columna diagnostico61: 38685 valores nulos
Columna diagnostico62: 38685 valores nulos
Columna diagnostico63: 38686 valores nulos
Columna diagnostico64: 38686 valores nulos
Columna diagnostico65: 38688 valores nulos
Columna diagnostico66: 38688 valores nulos
Columna diagnostico67: 38692 valores nulos
Columna diagnostico68: 38692 valores nulos
Columna diagnostico69: 38692 valores nulos
Columna diagnostico70: 38692 valores nulos
Columna diagnostico71: 38692 valores nulos
Columna diagnostico72: 38692 valores nulos
Columna diagnostico73: 38697 valores nulos
Columna diagnostico74: 38697 valores nulos
Columna diagnostico75: 38697 valores nulos
Columna diagnostico76: 38697 valores nulos
Columna diagnostico77: 38697 valores nulos
Columna diagnostico78: 38698 valores nulos
Columna diagnostico79: 38699 valores nulos
Columna diagnostico80: 38699 valores nulos
Columna diagnostico81: 38700 valores nulos
Columna diagnostico82: 38702 valores nulos
Columna diagnostico83: 38702 valores nulos
Columna numero_diagnosticos: 0 valores nulos

In [22]:
#Porcentaje de datos faltantes de la base completa
round(df_cronicos.isnull().sum().sum()/df_cronicos.size, 2)*100

57.99999999999999

**Filtrado de datos nulos de algunas variables**

In [23]:
df_cronicos[df_cronicos['presion_arterial_registro_medico'].isnull()]

,year,mes,fecha_diligenciamiento,hora,atencion,ingreso,tipo,nrodoc,peso,talla,...,diagnostico75,diagnostico76,diagnostico77,diagnostico78,diagnostico79,diagnostico80,diagnostico81,diagnostico82,diagnostico83,numero_diagnosticos
0,2017,Octubre,2/10/2017,9:00:20 a. m.,3912499,2629714,CC,311144,69.0,155.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,2017,Octubre,2/10/2017,9:04:33 a. m.,3942247,2629726,CC,308418,62.0,155.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,2017,Octubre,2/10/2017,9:11:43 a. m.,3898560,2629751,CC,308573,89.0,163.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,2017,Octubre,2/10/2017,9:33:34 a. m.,3912599,2629828,CC,307549,88.0,163.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,2017,Octubre,2/10/2017,9:43:59 a. m.,3906820,2629717,CC,307044,58.0,158.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38712,2022,Mayo,31/05/2022,10:55:31 p.m.,3419528,3630125,CC,308916,65.0,165.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
38713,2022,Mayo,31/05/2022,10:59:58 p.m.,5850632,4314997,CC,306248,60.0,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
38714,2022,Mayo,31/05/2022,11:13:57 p.m.,3413909,3630054,CC,310546,48.0,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
38715,2022,Mayo,31/05/2022,11:17:35 p.m.,5783823,4089709,CC,309601,60.0,165.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
38716,2022,Mayo,31/05/2022,11:25:39 p.m.,3991645,3434751,CC,311850,75.0,164.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [24]:
#Eliminación de variables con nombres parecidos
patron = re.compile("^diagnostico.*")

In [25]:
# Excluir una columna específica por nombre
columna_a_mantener = ['diagnostico_principal', 'diagnostico_epoc']

In [26]:
# Filtrar y eliminar columnas que coincidan con el patrón, excepto la columna a mantener
columnas_a_eliminar = [col for col in df_cronicos.columns if patron.match(col) and col != columna_a_mantener]

In [27]:
# Eliminar las columnas
df_cronicos = df_cronicos.drop(columns=columnas_a_eliminar)

In [28]:
df_cronicos.head()

,year,mes,fecha_diligenciamiento,hora,atencion,ingreso,tipo,nrodoc,peso,talla,...,ãlcera_de_pie_diabã©tico,remision,analisis_y_conducta_a_seguir,tiene_proximo_control,fecha_proximo_control,tipo_control,requiere_cita_de_morbilidad,fecha_cita_morbilidad,ambito_segun_el_medico,numero_diagnosticos
0,2017,Octubre,2/10/2017,9:00:20 a. m.,3912499,2629714,CC,311144,69.0,155.0,...,No,Grupal 2,ESTADIO RENAL 2 A3?RCV a 10 aÃ±os MODERADO **C...,ND,2/01/2018,Sin dato,ND,ND,Ambulatorio,0
1,2017,Octubre,2/10/2017,9:04:33 a. m.,3942247,2629726,CC,308418,62.0,155.0,...,No,Grupal 2,"Paciente 72 aÃ±os, Antecedente de. 1. HTA 2. E...",ND,2/01/2018,Sin dato,ND,ND,Domiciliario,0
2,2017,Octubre,2/10/2017,9:11:43 a. m.,3898560,2629751,CC,308573,89.0,163.0,...,No,Grupal 2,paciente con RCV alto por antecednete de enf. ...,ND,2/11/2017,Sin dato,ND,ND,Ambulatorio,0
3,2017,Octubre,2/10/2017,9:33:34 a. m.,3912599,2629828,CC,307549,88.0,163.0,...,No,Grupal 2,ESTADIO renal 2A1?RCV a 10 aÃ±os 16 % **CLASIF...,ND,2/01/2018,Sin dato,ND,ND,Ambulatorio,0
4,2017,Octubre,2/10/2017,9:43:59 a. m.,3906820,2629717,CC,307044,58.0,158.0,...,No,Grupal 3,"Paciente de 80 aÃ±os de edad, Con antecedentes...",ND,2/11/2017,Sin dato,ND,ND,Domiciliario,0

In [29]:
#Elimnación de variables puntuales
columnas_a_eliminar = ['fecha_cita_morbilidad', 'fecha_proximo_control','fecha_vacuna_neumococo_veintitres_valentes','fecha_vacuna_neumococo','fecha_basciloscopia','fecha_creatinina2','fecha_microalbuminuria','fecha_creatinina1','fecha_trigliceridos', 'fecha_colesterol_total','fecha_hdl',
                        'fecha_ldl','fecha_hemoglobina_glicosilada','fecha_glicemia']
df_cronicos = df_cronicos.drop(columnas_a_eliminar, axis=1)

In [30]:
#Eliminación de columnas
columnas_a_eliminar = ['tipo']
df_cronicos = df_cronicos.drop(columnas_a_eliminar, axis=1)

In [31]:
#Nulos de todos
for columna in df_cronicos.columns:
    valores_nulos = df_cronicos[columna].isnull().sum()
    print(f'Columna {columna}: {valores_nulos} valores nulos')

Columna year: 0 valores nulos
Columna mes: 0 valores nulos
Columna fecha_diligenciamiento: 0 valores nulos
Columna hora: 0 valores nulos
Columna atencion: 0 valores nulos
Columna ingreso: 0 valores nulos
Columna nrodoc: 0 valores nulos
Columna peso: 0 valores nulos
Columna talla: 0 valores nulos
Columna imc: 0 valores nulos
Columna clasificacion_imc: 0 valores nulos
Columna saturacion_de_oxigeno_(%): 140 valores nulos
Columna perimetro_muslo: 0 valores nulos
Columna perimetro_cintura: 0 valores nulos
Columna pliegue_triceps: 0 valores nulos
Columna pliegue_abdomen: 0 valores nulos
Columna pliegue_muslo: 0 valores nulos
Columna sumatoria_pliegues: 0 valores nulos
Columna presion_arterial_sistolica: 0 valores nulos
Columna presion_arterial_diastolica: 0 valores nulos
Columna frecuencia_cardiaca_en_reposo: 0 valores nulos
Columna auto-calificacion_nivel_de_ejercicio: 0 valores nulos
Columna constantes: 0 valores nulos
Columna mets_-indice_metabolico: 0 valores nulos
Columna vo2_-_maxima_cantidad_de_oxigeno: 0 valores nulos
Columna indice_de_fragilidad_groningen: 47 valores nulos
Columna calificacion_(indice_de_fragilidad): 0 valores nulos
Columna tiempo_en_segundos_(apoyo_monopodal): 0 valores nulos
Columna calificacion_(apoyo_monopodal): 0 valores nulos
Columna tiempo_en_segundos_(recorrer_5_metros): 0 valores nulos
Columna velocidad_(m/s): 0 valores nulos
Columna calificacion_velocidad: 0 valores nulos
Columna test_findrisc: 12760 valores nulos
Columna indice_tobillo/brazo: 18640 valores nulos
Columna observaciones: 27589 valores nulos
Columna presion_arterial_registro_medico: 22905 valores nulos
Columna diabetes_mellitus: 871 valores nulos
Columna tipo_diabetes_mellitus: 13693 valores nulos
Columna es_insulinorequiriente: 25893 valores nulos
Columna tiempo_con_el_diagnostico: 14670 valores nulos
Columna glicemia: 871 valores nulos
Columna hemoglobina_glicada: 871 valores nulos
Columna control_diabetes: 871 valores nulos
Columna tiene_riesgo_de_tener_diabetes_mellitus: 27886 valores nulos
Columna tiene_hta: 871 valores nulos
Columna control_hta: 10721 valores nulos
Columna tiene_riesgo_de_tener_hta: 10721 valores nulos
Columna tiempo_con_el_diagnostico1: 7001 valores nulos
Columna tiene_epoc: 871 valores nulos
Columna espirometria: 38684 valores nulos
Columna vef1/cvf: 38346 valores nulos
Columna vef1/vfc_posbroncodilatador: 38346 valores nulos
Columna gravedad: 38693 valores nulos
Columna disnea_mmrc: 38346 valores nulos
Columna clasificacion: 38695 valores nulos
Columna cat: 38346 valores nulos
Columna numero_de_exacerbaciones_ultimo_ano_(que_hayan_necesitado_hospitalizado): 38346 valores nulos
Columna clasificacion_gold: 38346 valores nulos
Columna clasificacion1: 38694 valores nulos
Columna clasificacion_bodex: 38346 valores nulos
Columna oxigeno_dependiente: 38685 valores nulos
Columna tiene_gases_arteriales: 38698 valores nulos
Columna resultado: 38673 valores nulos
Columna epoc_(clasificacion_bodex): 18000 valores nulos
Columna enfermedad_coronaria_(en_el_ãºltimo_aã±o): 871 valores nulos
Columna insuficiencia_cardiaca: 871 valores nulos
Columna valvulopatia: 871 valores nulos
Columna arritmia_o_paciente_con_dispositivo: 871 valores nulos
Columna sufre_de_alguna_enfermedad_cardiovascular: 871 valores nulos
Columna i¿cual?: 22144 valores nulos
Columna tabaquismo: 1053 valores nulos
Columna cuantos_cigarrillos_dia: 785 valores nulos
Columna anos_de_consumo: 13072 valores nulos
Columna indice_paquete/ano: 34579 valores nulos
Columna lipoproteina: 1053 valores nulos
Columna hdl: 1053 valores nulos
Columna colesterol_total: 1053 valores nulos
Columna trigliceridos: 1053 valores nulos
Columna clasificacion_de_framinghan: 8670 valores nulos
Columna creatinina_1_consulta: 1053 valores nulos
Columna tasa_de_filtracion_glomerular_tfg: 1053 valores nulos
Columna estadio_de_la_enfermedad_renal: 3248 valores nulos
Columna microalbuminuria: 1053 valores nulos
Columna hormona_estimulante_de_la_tiroides_(tsh): 1053 valores nulos
Columna otras_morbilidades: 38715 valores nulos
Columna clase_funcional: 1053 valores nulos
Columna creatinina_2_consulta: 1053 valores nulos
Columna tasa_de_filtracion_glomerular_tfg2: 1053 valores nulos
Columna meses_de_diferencia_entre_tfg: 1053 valores nulos
Columna cambio_de_tfg: 1053 valores nulos
Columna clasificacion_cambio_de_tfg: 21929 valores nulos
Columna ãltima_mamografã­a: 37105 valores nulos
Columna ãltima_citologã­a: 37604 valores nulos
Columna ãltima_cita_odontolã³gica: 36221 valores nulos
Columna ãltima_cita_con_optometrã­a_/_oftallmologã­a: 34996 valores nulos
Columna ãltimo_psa: 36282 valores nulos
Columna basciloscopia: 20282 valores nulos
Columna ãltima_vacuna_de_influenza: 36540 valores nulos
Columna ãlcera_de_pie_diabã©tico: 3504 valores nulos
Columna remision: 1053 valores nulos
Columna analisis_y_conducta_a_seguir: 1055 valores nulos
Columna tiene_proximo_control: 13570 valores nulos
Columna tipo_control: 14279 valores nulos
Columna requiere_cita_de_morbilidad: 13570 valores nulos
Columna ambito_segun_el_medico: 13067 valores nulos
Columna numero_diagnosticos: 0 valores nulos

In [32]:
df_cronicos

,year,mes,fecha_diligenciamiento,hora,atencion,ingreso,nrodoc,peso,talla,imc,...,basciloscopia,ãltima_vacuna_de_influenza,ãlcera_de_pie_diabã©tico,remision,analisis_y_conducta_a_seguir,tiene_proximo_control,tipo_control,requiere_cita_de_morbilidad,ambito_segun_el_medico,numero_diagnosticos
0,2017,Octubre,2/10/2017,9:00:20 a. m.,3912499,2629714,311144,69.0,155.0,28.72,...,NaN,NaN,No,Grupal 2,ESTADIO RENAL 2 A3?RCV a 10 aÃ±os MODERADO **C...,ND,Sin dato,ND,Ambulatorio,0
1,2017,Octubre,2/10/2017,9:04:33 a. m.,3942247,2629726,308418,62.0,155.0,25.81,...,NaN,NaN,No,Grupal 2,"Paciente 72 aÃ±os, Antecedente de. 1. HTA 2. E...",ND,Sin dato,ND,Domiciliario,0
2,2017,Octubre,2/10/2017,9:11:43 a. m.,3898560,2629751,308573,89.0,163.0,33.50,...,NaN,NaN,No,Grupal 2,paciente con RCV alto por antecednete de enf. ...,ND,Sin dato,ND,Ambulatorio,0
3,2017,Octubre,2/10/2017,9:33:34 a. m.,3912599,2629828,307549,88.0,163.0,33.12,...,NaN,NaN,No,Grupal 2,ESTADIO renal 2A1?RCV a 10 aÃ±os 16 % **CLASIF...,ND,Sin dato,ND,Ambulatorio,0
4,2017,Octubre,2/10/2017,9:43:59 a. m.,3906820,2629717,307044,58.0,158.0,23.23,...,NaN,NaN,No,Grupal 3,"Paciente de 80 aÃ±os de edad, Con antecedentes...",ND,Sin dato,ND,Domiciliario,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38712,2022,Mayo,31/05/2022,10:55:31 p.m.,3419528,3630125,308916,65.0,165.0,23.88,...,Aplica Negativo,NaN,No,Grupal 4,Plan: - Visita medica en 2 meses - ParaclÃ­nic...,NaN,NaN,NaN,NaN,0
38713,2022,Mayo,31/05/2022,10:59:58 p.m.,5850632,4314997,306248,60.0,160.0,23.44,...,NaN,NaN,No,Grupal 4,Plan: - Control por medicina general en un mes...,NaN,NaN,NaN,NaN,0
38714,2022,Mayo,31/05/2022,11:13:57 p.m.,3413909,3630054,310546,48.0,160.0,18.75,...,NaN,NaN,No,Grupal 4,Plan: - Control por medicina general en dos me...,NaN,NaN,NaN,NaN,0
38715,2022,Mayo,31/05/2022,11:17:35 p.m.,5783823,4089709,309601,60.0,165.0,22.04,...,Aplica Negativo,NaN,No,Grupal 4,Plan: - Visita domiciliaria control dentro de ...,Si,MÃ©dico,No,Domiciliario,1
38716,2022,Mayo,31/05/2022,11:25:39 p.m.,3991645,3434751,311850,75.0,164.0,27.89,...,NaN,NaN,No,Grupal 4,Plan: - Control por medicina general en un mes...,NaN,NaN,NaN,NaN,0

In [33]:
#Pacientes unicos
print('Se tienen', len(df_cronicos['nrodoc'].unique()), 'pacientes únicos en los datos.')

Se tienen 6099 pacientes únicos en los datos.

**Tratamiento de datos de diagnóstico**